version: "3.9"  # optional since v1.27.0
services:
  ipa-downloader:
    image: "${IPA_DOWNLOADER_IMAGE}"
    command: "/usr/local/bin/get-resource.sh"
    env_file:
      - .env
    volumes:
      - ${IRONIC_DATA_DIR}:/shared

  dnsmasq:
    image: "${IRONIC_IMAGE}"
    entrypoint: /entrypoint.sh
    command : /bin/rundnsmasq
    network_mode: host
    env_file:
      - .env
    volumes:
      - ${IRONIC_DATA_DIR}:/shared
      - ${IRONIC_SRC_DIR}:/src
      - ./entrypoint.sh:/entrypoint.sh

  mariadb:
    image: "${IRONIC_IMAGE}"
    entrypoint: /entrypoint.sh
    command : /bin/runmariadb
    network_mode: host
    env_file:
      - .env
    volumes:
      - ${IRONIC_DATA_DIR}:/shared
      - ${IRONIC_SRC_DIR}:/src
      - ./entrypoint.sh:/entrypoint.sh

  api:
    image: "${IRONIC_IMAGE}"
    entrypoint: /entrypoint.sh
    command : /bin/runironic-api
    network_mode: host
    env_file:
      - .env
    volumes:
      - ${IRONIC_DATA_DIR}:/shared
      - ${IRONIC_SRC_DIR}:/src
      - ./entrypoint.sh:/entrypoint.sh

  conductor:
    image: "${IRONIC_IMAGE}"
    entrypoint: /entrypoint.sh
    command : /bin/runironic-conductor
    network_mode: host
    env_file:
      - .env
    volumes:
      - ${IRONIC_DATA_DIR}:/shared
      - ${IRONIC_SRC_DIR}:/src
      - ./entrypoint.sh:/entrypoint.sh

  inspector:
    image: "${IRONIC_IMAGE}"
    entrypoint: /entrypoint.sh
    command : /bin/runironic-inspector
    network_mode: host
    env_file:
      - .env
    volumes:
      - ${IRONIC_DATA_DIR}:/shared
      - ${IRONIC_SRC_DIR}:/src
      - ./entrypoint.sh:/entrypoint.sh

  log-watch:
    image: "${IRONIC_IMAGE}"
    entrypoint: /entrypoint.sh
    command : /bin/runlogwatch.sh
    volumes:
      - ${IRONIC_DATA_DIR}:/shared
      - ${IRONIC_SRC_DIR}:/src
      - ./entrypoint.sh:/entrypoint.sh
