version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
    build:
      context: ..
      dockerfile: Dockerfile
    image: netbox:latest-plugins
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ../initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
