services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    volumes:
      - zookeeper:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - kafka:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://${SERVICE_IP}:9092,EXTERNAL://${SERVICE_IP}:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  dicious:
    build: dicious
    command: ["-d", "/data/dicious.db", "kafka:9092"]
    volumes:
      - dicious-db:/data
    environment:
      DICIOUS_LOG: DEBUG
      KAFKA_TOPIC: notifications.info
    depends_on:
      - kafka

volumes:
  zookeeper:
  kafka:
  dicious-db:
